name: Lint and Test

on: [push, pull_request]

jobs:
  lint:
    name: Lint
    strategy:
      matrix:
        node: ['14', '16', '18']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3.1.1
        with:
          node-version: ${{ matrix.node }}
      - run: npm install
      - run: npm run lint
  test:
    name: Test
    strategy:
      matrix:
        node: ['14', '16', '18']
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3.1.1
        with:
          node-version: ${{ matrix.node }}
      - run: npm install
      - run: npm test
  release:
    name: Release to NPM
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3.1.1
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org/'
      - run: npm install
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
